name: CI

on: [ push, workflow_dispatch ]

jobs:
  ubuntu:
    name: ubuntu-24_04
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4 # TODO: configure, see https://github.com/actions/setup-dotnet 
        with:
          dotnet-version: |
            8.0.x
            9.0.x
          dotnet-quality: ga
      #      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
      #        uses: actions/cache@v4
      #        with:
      #          path: |
      #            # .nuke/temp 
      #            ~/.nuget/packages
      #          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'build build'
        run: dotnet build build/build.csproj -c Release --nologo -v m
      - name: 'run build'
        run: dotnet run --project build/build.csproj -c Release --no-build -- pack
        env:
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
      - name: 'publish: test-results'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: artifacts/test-results
      - name: 'publish: packages'
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
